### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by siruguri** [ResidentMario/mysite#1]
Would you consider adding an RSS feed to your site for your blog? I would like to add it to my RSS reader. :)

**Comment by ResidentMario** [comment]
Yes---several people have asked for this feature! I spent a chunk of time today polishing the CSS, but a bunch of improvements to underlying Python code are on my to-do list. This is at the top of them. I will let you know when it is done---hopefully I will be able to get to it by next weekend.

**Comment by ResidentMario** [comment]
I have added an RSS feed to the site, available [here](http://www.residentmar.io/feed). I haven't yet implemented scraping off article summaries, but it should hopefully be usable. Let me know if you have any issues, and thank you for the interest!

**Comment by siruguri** [comment]
It works! Thanks. :)
